# sonar-project.properties

sonar.projectKey=sonar-qube-poc
sonar.host.url=http://localhost:9000

# source code location
sonar.sources=src
sonar.inclusions=**/*.py
sonar.tests=tests

# Exclude files in the 'venv' or 'virtualenv' directories;
# Completely ignore files from analysis
sonar.exclusions=**/venv_sonar/**, **/venv/**, **/.ruff_cache/**

# Ignore duplication detection for test files; 
# Ignore only duplication detection
sonar.cpd.exclusions=tests/**

# Ignore from coverage calculation
sonar.coverage.exclusions=tests/**

# code coverage settings
sonar.python.coverage.reportPaths=coverage.xml

# encoding
sonar.sourceEncoding=UTF-8

# language
#sonar.python.version=3.14


# External linters
sonar.python.ruff.reportPaths=ruff-report.json
sonar.python.pylint.reportPaths=pylint-report.txt

# disable when inside a Git repo.
# sonar.scm.disabled=true

# update version before each release:
# sonar.projectVersion=1.1



